board/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.board_list, name='board_list'),
    url(r'^(?P<id>\d+)/$', views.board_detail, name='board_detail'),
    url(r'^new/$', views.board_new, name='board_new'),
]

mandarart/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.shortcuts import redirect
from django.conf.urls import include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^board/', include(('board.urls', 'board'), namespace='board')),
    url(r'^$', lambda r: redirect('board:board_list'), name='root'),
]

mandarart/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    {% load static %}
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="{% static "jquery-3.2.1.min.js" %}"></script>
    {% block script %}{% endblock %}
    <link rel="stylesheet" href="{% static "style.css" %}">
    <link rel="stylesheet" href="{% static "bootstrap.css" %}">

    <title>
        {% block title %}
            Mandarart
        {% endblock %}
    </title>

</head>
<body>
<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Mandarart</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation" style="">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor03">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url "board:board_list" %}">List</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url "board:board_new" %}">write</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">About</a>
                </li>
            </ul>
{#            <form class="form-inline my-2 my-lg-0">#}
{#                <input class="form-control mr-sm-2" type="text" placeholder="Search">#}
{#                <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>#}
{#            </form>#}
        </div>
    </nav>
<div class="container">
    <div class="row">
        <div class="col-sm-12 banner">
            {% block banner %}
            {% endblock %}
        </div>
    </div>
</div>
    <div class="row">
        <div class="col-sm-12">
            {% block content %}
            {% endblock %}

        </div>
    </div>
</div>
{#<nav class="navbar navbar-default">#}
{#    <div class="container">#}
{#        <div class="navbar-header">#}
{#            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">#}
{#                <span class="icon-bar"></span>#}
{#                <span class="icon-bar"></span>#}
{#                <span class="icon-bar"></span>#}
{#            </button>#}
{#            <a class="navbar-brand" href="#">Mandarart</a>#}
{#        </div>#}
{#        <div id="navbar" class="collapse navbar-collapse">#}
{#            <ul class="nav navbar-nav">#}
{#                <li class="active"><a href="{% url "root" %}">Home</a></li>#}
{#                <li><a href="#">About</a></li>#}
{#                <li><a href="#">Contact</a></li>#}
{#            </ul>#}
{#            <ul class="nav navbar-nav navbar-right">#}
{#                <li><a href="#">회원가입</a></li>#}
{#                <li><a href="#">로그인</a></li>#}
{#            </ul>#}
{#        </div>#}
{#        <div class="row">#}
{#            <div class="col-sm-12 banner">#}
{#                {% block banner %}#}
{#                {% endblock %}#}
{#            </div>#}
{#        </div>#}
{#        <div class="row">#}
{#            <div class="col-sm-12">#}
{#                {% block content %}#}
{#                {% endblock %}#}
{##}
{#            </div>#}
{#        </div>#}
{#    </div>#}
{#</nav>#}

</body>
</html>