board/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.board_list, name='board_list'),
    url(r'^(?P<id>\d+)/$', views.board_detail, name='board_detail'),
    url(r'^new/$', views.board_new, name='board_new'),
]

mandarart/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.shortcuts import redirect
from django.conf.urls import include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^board/', include(('board.urls', 'board'), namespace='board')),
    url(r'^$', lambda r: redirect('board:board_list'), name='root'),
]

board/models.py
from django.db import models
from django.urls import reverse


class MainGoal(models.Model):
    main_goal = models.CharField(max_length=20)
    writer = models.CharField(max_length=30)
    ins_dt = models.DateTimeField(auto_now_add=True)
    upd_dt = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.main_goal

    def get_absolute_url(self):
        return reverse('board:board_list', args=[self.id])


class SubGoal(models.Model):
    main_goal = models.ForeignKey(MainGoal, on_delete=models.CASCADE)
    sub_id = models.SmallIntegerField()
    sub_goal = models.CharField(max_length=30)
    ins_dt = models.DateTimeField(auto_now_add=True)
    upd_dt = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.sub_goal


class AchWay(models.Model):
    sub_goal = models.ForeignKey(SubGoal, on_delete=models.CASCADE)
    ach_way = models.CharField(max_length=50)
    sub_id = models.SmallIntegerField()
    ins_dt = models.DateTimeField(auto_now_add=True)
    upd_dt = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.ach_way

board/forms.py
from django import forms


class MainForm(forms.Form):
    main_goal = forms.CharField(max_length=20, label='핵심 목표')
    writer = forms.CharField(max_length=30, label='작성자')
    sub_goal1 = forms.CharField(max_length=30, label='세부 목표 1')
    sub_goal2 = forms.CharField(max_length=30, label='세부 목표 2')
    sub_goal3 = forms.CharField(max_length=30, label='세부 목표 3')
    sub_goal4 = forms.CharField(max_length=30, label='세부 목표 4')
    sub_goal5 = forms.CharField(max_length=30, label='세부 목표 5')
    sub_goal6 = forms.CharField(max_length=30, label='세부 목표 6')
    sub_goal7 = forms.CharField(max_length=30, label='세부 목표 7')
    sub_goal8 = forms.CharField(max_length=30, label='세부 목표 8')


class SubForm1(forms.Form):
    ach_way11 = forms.CharField(max_length=50, label='달성 방법 1')
    ach_way12 = forms.CharField(max_length=50, label='달성 방법 2')
    ach_way13 = forms.CharField(max_length=50, label='달성 방법 3')
    ach_way14 = forms.CharField(max_length=50, label='달성 방법 4')
    ach_way15 = forms.CharField(max_length=50, label='달성 방법 5')
    ach_way16 = forms.CharField(max_length=50, label='달성 방법 6')
    ach_way17 = forms.CharField(max_length=50, label='달성 방법 7')
    ach_way18 = forms.CharField(max_length=50, label='달성 방법 8')


class SubForm2(forms.Form):
    ach_way21 = forms.CharField(max_length=50, label='달성 방법 1')
    ach_way22 = forms.CharField(max_length=50, label='달성 방법 2')
    ach_way23 = forms.CharField(max_length=50, label='달성 방법 3')
    ach_way24 = forms.CharField(max_length=50, label='달성 방법 4')
    ach_way25 = forms.CharField(max_length=50, label='달성 방법 5')
    ach_way26 = forms.CharField(max_length=50, label='달성 방법 6')
    ach_way27 = forms.CharField(max_length=50, label='달성 방법 7')
    ach_way28 = forms.CharField(max_length=50, label='달성 방법 8')


class SubForm3(forms.Form):
    ach_way31 = forms.CharField(max_length=50, label='달성 방법 1')
    ach_way32 = forms.CharField(max_length=50, label='달성 방법 2')
    ach_way33 = forms.CharField(max_length=50, label='달성 방법 3')
    ach_way34 = forms.CharField(max_length=50, label='달성 방법 4')
    ach_way35 = forms.CharField(max_length=50, label='달성 방법 5')
    ach_way36 = forms.CharField(max_length=50, label='달성 방법 6')
    ach_way37 = forms.CharField(max_length=50, label='달성 방법 7')
    ach_way38 = forms.CharField(max_length=50, label='달성 방법 8')


class SubForm4(forms.Form):
    ach_way41 = forms.CharField(max_length=50, label='달성 방법 1')
    ach_way42 = forms.CharField(max_length=50, label='달성 방법 2')
    ach_way43 = forms.CharField(max_length=50, label='달성 방법 3')
    ach_way44 = forms.CharField(max_length=50, label='달성 방법 4')
    ach_way45 = forms.CharField(max_length=50, label='달성 방법 5')
    ach_way46 = forms.CharField(max_length=50, label='달성 방법 6')
    ach_way47 = forms.CharField(max_length=50, label='달성 방법 7')
    ach_way48 = forms.CharField(max_length=50, label='달성 방법 8')


class SubForm5(forms.Form):
    ach_way51 = forms.CharField(max_length=50, label='달성 방법 1')
    ach_way52 = forms.CharField(max_length=50, label='달성 방법 2')
    ach_way53 = forms.CharField(max_length=50, label='달성 방법 3')
    ach_way54 = forms.CharField(max_length=50, label='달성 방법 4')
    ach_way55 = forms.CharField(max_length=50, label='달성 방법 5')
    ach_way56 = forms.CharField(max_length=50, label='달성 방법 6')
    ach_way57 = forms.CharField(max_length=50, label='달성 방법 7')
    ach_way58 = forms.CharField(max_length=50, label='달성 방법 8')


class SubForm6(forms.Form):
    ach_way61 = forms.CharField(max_length=50, label='달성 방법 1')
    ach_way62 = forms.CharField(max_length=50, label='달성 방법 2')
    ach_way63 = forms.CharField(max_length=50, label='달성 방법 3')
    ach_way64 = forms.CharField(max_length=50, label='달성 방법 4')
    ach_way65 = forms.CharField(max_length=50, label='달성 방법 5')
    ach_way66 = forms.CharField(max_length=50, label='달성 방법 6')
    ach_way67 = forms.CharField(max_length=50, label='달성 방법 7')
    ach_way68 = forms.CharField(max_length=50, label='달성 방법 8')


class SubForm7(forms.Form):
    ach_way1 = forms.CharField(max_length=50, label='달성 방법 1')
    ach_way2 = forms.CharField(max_length=50, label='달성 방법 2')
    ach_way3 = forms.CharField(max_length=50, label='달성 방법 3')
    ach_way4 = forms.CharField(max_length=50, label='달성 방법 4')
    ach_way5 = forms.CharField(max_length=50, label='달성 방법 5')
    ach_way6 = forms.CharField(max_length=50, label='달성 방법 6')
    ach_way7 = forms.CharField(max_length=50, label='달성 방법 7')
    ach_way8 = forms.CharField(max_length=50, label='달성 방법 8')


class SubForm8(forms.Form):
    ach_way1 = forms.CharField(max_length=50, label='달성 방법 1')
    ach_way2 = forms.CharField(max_length=50, label='달성 방법 2')
    ach_way3 = forms.CharField(max_length=50, label='달성 방법 3')
    ach_way4 = forms.CharField(max_length=50, label='달성 방법 4')
    ach_way5 = forms.CharField(max_length=50, label='달성 방법 5')
    ach_way6 = forms.CharField(max_length=50, label='달성 방법 6')
    ach_way7 = forms.CharField(max_length=50, label='달성 방법 7')
    ach_way8 = forms.CharField(max_length=50, label='달성 방법 8')

board/views.py
from django.shortcuts import render, redirect
from .models import MainGoal, SubGoal, AchWay
from django.shortcuts import get_object_or_404
from .forms import MainForm, SubForm1, SubForm2, SubForm3, SubForm4, SubForm5, SubForm6, SubForm7, SubForm8
from django.core.exceptions import ObjectDoesNotExist
# Create your views here.


def board_list(request):
    qs = MainGoal.objects.all()

    return render(request, 'board/board_list.html', {
        'board_list': qs,
    })


def board_detail(request, id):
    maingoal = get_object_or_404(MainGoal, id=id)
    subgoal_list = []
    ach_way_list = []
    for index in range(1, 9):
        try :
            subgoal = SubGoal.objects.get(main_goal=maingoal, sub_id=index)
            subgoal_list.append(subgoal)

            for ach_index in range(1, 9):
                if AchWay.objects.get(sub_goal=subgoal, sub_id=ach_index):
                    ach_way_list.append((AchWay.objects.get(sub_goal=SubGoal, sub_id=ach_index)))
                else:
                    ach_way_list.append('')
        except ObjectDoesNotExist:
            subgoal_list.append('')

    # achway11 = AchWay.objects.get(sub_goal=subgoal1, id=1)
    return render(request, 'board/board_detail.html', {
        'maingoal': maingoal,
        'subgoal1': subgoal_list[0],
        'subgoal2': subgoal_list[1],
        'subgoal3': subgoal_list[2],
        'subgoal4': subgoal_list[3],
        'subgoal5': subgoal_list[4],
        'subgoal6': subgoal_list[5],
        'subgoal7': subgoal_list[6],
        'subgoal8': subgoal_list[7],
        'ach_way_list': ach_way_list,
    })


def board_new(request):
    if request.method == 'POST':
        main_form = MainForm(request.POST)
        sub_form1 = SubForm1(request.POST)
        sub_form2 = SubForm2(request.POST)
        sub_form3 = SubForm3(request.POST)
        sub_form4 = SubForm4(request.POST)
        sub_form5 = SubForm5(request.POST)
        sub_form6 = SubForm6(request.POST)
        sub_form7 = SubForm7(request.POST)
        sub_form8 = SubForm8(request.POST)

        sub_form_list = [sub_form1, sub_form2, sub_form3, sub_form4, sub_form5, sub_form6, sub_form7, sub_form8]
        if main_form.is_valid():
            maingoal = MainGoal()
            maingoal.main_goal = main_form.cleaned_data['main_goal']
            maingoal.writer = main_form.cleaned_data['writer']
            maingoal.save()
            main_id = maingoal.id

            for index in range(1, 9):
                subgoal = SubGoal()
                subgoal.main_goal = maingoal
                subgoal.sub_goal = main_form.cleaned_data['sub_goal' + str(index)]
                subgoal.sub_id = index
                subgoal.save()

                for index2 in range(0, 8):
                    if sub_form_list[index2].is_valid():
                        ach_way = AchWay()
                        ach_way.sub_goal = subgoal
                        ach_way.ach_way = sub_form_list[index2].cleaned_data['ach_way' + str(index) + str(index2 + 1)]
                        ach_way.sub_id = index2 + 1
                        ach_way.save()

            return redirect('board:board_list')
    else:
        sub_form1 = SubForm1()
        sub_form2 = SubForm2()
        sub_form3 = SubForm3()
        sub_form4 = SubForm4()
        sub_form5 = SubForm5()
        sub_form6 = SubForm6()
        sub_form7 = SubForm7()
        sub_form8 = SubForm8()

    return render(request, 'board/board_new.html', {
        'sub_forms': (sub_form1, sub_form2, sub_form3, sub_form4,
                      sub_form5, sub_form6, sub_form7, sub_form8,),
        # 'sub_form1': sub_form1,
        # 'sub_form2': sub_form2,
        # 'sub_form3': sub_form3,
        # 'sub_form4': sub_form4,
        # 'sub_form5': sub_form5,
        # 'sub_form6': sub_form6,
        # 'sub_form7': sub_form7,
        # 'sub_form8': sub_form8,
    })

board/templates/board/board_list.html
{% extends 'board/layout.html' %}
{% block content %}
    <table>
        <tr>
            {% for goal in board_list %}
                {% if forloop.counter0|divisibleby:5 %}
                    </tr><tr>
                {% endif %}
                <td>
                    <div class="card border-primary mb-3" style="max-width: 20rem;">
                        <div class="card-header">{{ goal.ins_dt|timesince }}전 작성</div>
                        <div class="card-body text-primary">
                            <h4 class="card-title"><a href="{% url "board:board_detail" goal.id %}">{{ goal.writer }}님의 {{ goal.main_goal }}</a></h4>
                            <p class="card-text"></p>
                        </div>
                    </div>
                </td>
            {% endfor %}
        </tr>
    </table>
{% endblock %}

board/templates/board/board_new.html
{% extends 'board/layout.html' %}
{% block script %}
    {% load static %}
    <script type="text/javascript" src="{% static "board/board_new.js" %}"></script>
    <script type="text/javascript" src="{% static "board/assets/script/vue.js" %}"></script>

{% endblock %}
{% block banner %}
    <div>
        <h3> 쓰기쓰기쓰기. </h3>
    </div>
{% endblock %}
{% block content %}
    <div id="content-wrapper">
        <div id="table-wrapper">
            <table id="goal_table">
                <tr id="line1" class="table-active">
                    <td>
                        <div id="ach_way11">[/goal.ach[0][0]/]</div>
                    </td>
                    <td>
                        <div id="ach_way12">[/goal.ach[0][1]/]</div>
                    </td>
                    <td>
                        <div id="ach_way13">[/goal.ach[0][2]/]</div>
                    </td>
                    <td>
                        <div id="ach_way21">[/goal.ach[1][0]/]</div>
                    </td>
                    <td>
                        <div id="ach_way22">[/goal.ach[1][1]/]</div>
                    </td>
                    <td>
                        <div id="ach_way23">[/goal.ach[1][2]/]</div>
                    </td>
                    <td>
                        <div id="ach_way31">[/goal.ach[2][0]/]</div>
                    </td>
                    <td>
                        <div id="ach_way32">[/goal.ach[2][1]/]</div>
                    </td>
                    <td>
                        <div id="ach_way33">[/goal.ach[2][2]/]</div>
                    </td>
                </tr>
                <tr id="line2" class="table-active">
                    <td>
                        <div id="ach_way14">[/goal.ach[0][3]/]</div>
                    </td>
                    <td>
                        <div class="sub_goal_cell1">[/goal.sub[0]/]</div>
                    </td>
                    <td>
                        <div id="ach_way15">[/goal.ach[0][4]/]</div>
                    </td>
                    <td>
                        <div id="ach_way24">[/goal.ach[1][3]/]</div>
                    </td>
                    <td>
                        <div class="sub_goal_cell2">[/goal.sub[1]/]</div>
                    </td>
                    <td>
                        <div id="ach_way25">[/goal.ach[1][4]/]</div>
                    </td>
                    <td>
                        <div id="ach_way34">[/goal.ach[2][3]/]</div>
                    </td>
                    <td>
                        <div class="sub_goal_cell3">[/goal.sub[2]/]</div>
                    </td>
                    <td>
                        <div id="ach_way35">[/goal.ach[2][4]/]</div>
                    </td>
                </tr>
                <tr id="line3" class="table-active">
                    <td>
                        <div id="ach_way16">[/goal.ach[0][5]/]</div>
                    </td>
                    <td>
                        <div id="ach_way17">[/goal.ach[0][6]/]</div>
                    </td>
                    <td>
                        <div id="ach_way18">[/goal.ach[0][7]/]</div>
                    </td>
                    <td>
                        <div id="ach_way26">[/goal.ach[1][5]/]</div>
                    </td>
                    <td>
                        <div id="ach_way27">[/goal.ach[1][6]/]</div>
                    </td>
                    <td>
                        <div id="ach_way28">[/goal.ach[1][7]/]</div>
                    </td>
                    <td>
                        <div id="ach_way36">[/goal.ach[2][5]/]</div>
                    </td>
                    <td>
                        <div id="ach_way37">[/goal.ach[2][6]/]</div>
                    </td>
                    <td>
                        <div id="ach_way38">[/goal.ach[2][7]/]</div>
                    </td>
                </tr>
                <tr id="line4" class="table-active">
                    <td>
                        <div id="ach_way41">[/goal.ach[3][0]/]</div>
                    </td>
                    <td>
                        <div id="ach_way42">[/goal.ach[3][1]/]</div>
                    </td>
                    <td>
                        <div id="ach_way43">[/goal.ach[3][2]/]</div>
                    </td>
                    <td>
                        <div class="sub_goal_cell1">[/goal.sub[0]/]</div>
                    </td>
                    <td>
                        <div class="sub_goal_cell2">[/goal.sub[1]/]</div>
                    </td>
                    <td>
                        <div class="sub_goal_cell3">[/goal.sub[2]/]</div>
                    </td>
                    <td>
                        <div id="ach_way51">[/goal.ach[4][0]/]</div>
                    </td>
                    <td>
                        <div id="ach_way52">[/goal.ach[4][1]/]</div>
                    </td>
                    <td>
                        <div id="ach_way53">[/goal.ach[4][2]/]</div>
                    </td>
                </tr>
                <tr id="line5" class="table-active">
                    <td>
                        <div id="ach_way44">[/goal.ach[3][3]/]</div>
                    </td>
                    <td>
                        <div class="sub_goal_cell4">[/goal.sub[3]/]</div>
                    </td>
                    <td>
                        <div id="ach_way45">[/goal.ach[3][4]/]</div>
                    </td>
                    <td>
                        <div class="sub_goal_cell4">[/goal.sub[3]/]</div>
                    </td>
                    <td>
                        <div id="main_goal_cell">[/goal.main/]</div>
                    </td>
                    <td>
                        <div class="sub_goal_cell5">[/goal.sub[4]/]</div>
                    </td>
                    <td>
                        <div id="ach_way54">[/goal.ach[4][3]/]</div>
                    </td>
                    <td>
                        <div class="sub_goal_cell5">[/goal.sub[4]/]</div>
                    </td>
                    <td>
                        <div id="ach_way55">[/goal.ach[4][4]/]</div>
                    </td>
                </tr>
                <tr id="line6" class="table-active">
                    <td>
                        <div id="ach_way46">[/goal.ach[3][5]/]</div>
                    </td>
                    <td>
                        <div id="ach_way47">[/goal.ach[3][6]/]</div>
                    </td>
                    <td>
                        <div id="ach_way48">[/goal.ach[3][7]/]</div>
                    </td>
                    <td>
                        <div class="sub_goal_cell6">[/goal.sub[5]/]</div>
                    </td>
                    <td>
                        <div class="sub_goal_cell7">[/goal.sub[6]/]</div>
                    </td>
                    <td>
                        <div class="sub_goal_cell8">[/goal.sub[7]/]</div>
                    </td>
                    <td>
                        <div id="ach_way56">[/goal.ach[4][5]/]</div>
                    </td>
                    <td>
                        <div id="ach_way57">[/goal.ach[4][6]/]</div>
                    </td>
                    <td>
                        <div id="ach_way58">[/goal.ach[4][7]/]</div>
                    </td>
                </tr>
                <tr id="line7" class="table-active">
                    <td>
                        <div id="ach_way61">[/goal.ach[5][0]/]</div>
                    </td>
                    <td>
                        <div id="ach_way62">[/goal.ach[5][1]/]</div>
                    </td>
                    <td>
                        <div id="ach_way63">[/goal.ach[5][2]/]</div>
                    </td>
                    <td>
                        <div id="ach_way71">[/goal.ach[6][0]/]</div>
                    </td>
                    <td>
                        <div id="ach_way72">[/goal.ach[6][1]/]</div>
                    </td>
                    <td>
                        <div id="ach_way73">[/goal.ach[6][2]/]</div>
                    </td>
                    <td>
                        <div id="ach_way81">[/goal.ach[7][0]/]</div>
                    </td>
                    <td>
                        <div id="ach_way82">[/goal.ach[7][1]/]</div>
                    </td>
                    <td>
                        <div id="ach_way83">[/goal.ach[7][2]/]</div>
                    </td>
                </tr>
                <tr id="line8" class="table-active">
                    <td>
                        <div id="ach_way64">[/goal.ach[5][3]/]</div>
                    </td>
                    <td>
                        <div class="sub_goal_cell6">[/goal.sub[5]/]</div>
                    </td>
                    <td>
                        <div id="ach_way65">[/goal.ach[5][4]/]</div>
                    </td>
                    <td>
                        <div id="ach_way74">[/goal.ach[6][3]/]</div>
                    </td>
                    <td>
                        <div class="sub_goal_cell7">[/goal.sub[6]/]</div>
                    </td>
                    <td>
                        <div id="ach_way75">[/goal.ach[6][4]/]</div>
                    </td>
                    <td>
                        <div id="ach_way84">[/goal.ach[7][3]/]</div>
                    </td>
                    <td>
                        <div class="sub_goal_cell8">[/goal.sub[7]/]</div>
                    </td>
                    <td>
                        <div id="ach_way85">[/goal.ach[7][4]/]</div>
                    </td>
                </tr>
                <tr id="line9" class="table-active">
                    <td>
                        <div id="ach_way66">[/goal.ach[5][5]/]</div>
                    </td>
                    <td>
                        <div id="ach_way67">[/goal.ach[5][6]/]</div>
                    </td>
                    <td>
                        <div id="ach_way68">[/goal.ach[5][7]/]</div>
                    </td>
                    <td>
                        <div id="ach_way76">[/goal.ach[6][5]/]</div>
                    </td>
                    <td>
                        <div id="ach_way77">[/goal.ach[6][6]/]</div>
                    </td>
                    <td>
                        <div id="ach_way78">[/goal.ach[6][7]/]</div>
                    </td>
                    <td>
                        <div id="ach_way86">[/goal.ach[7][5]/]</div>
                    </td>
                    <td>
                        <div id="ach_way87">[/goal.ach[7][6]/]</div>
                    </td>
                    <td>
                        <div id="ach_way88">[/goal.ach[7][7]/]</div>
                    </td>
                </tr>
            </table>
        </div>
        <div id="form-wrapper">
            <div id="main_input">
                <form id="main_form" action="" method="POST">
                    {% csrf_token %}
                    <table>
                        <tr>
                            <th>핵심 목표 :</th>
                            <td>
                                <input type="text" name="main_goal" maxlength="20" required="" id="id_main_goal"
                                       v-model="goal.main">
                            </td>
                            <td>
                            </td>
                        </tr>
                        <tr>
                            <th>작성자 :</th>
                            <td>
                                <input type="text" name="writer" maxlength="30" required="" id="id_writer">
                            </td>
                            <td>
                            </td>
                        </tr>
                        {% for index in '12345678' %}
                            <tr>
                                <th>세부 목표 {{ index }} :</th>
                                <td>
                                    <input type="text" name="sub_goal{{ index }}" maxlength="30" required="" id="id_sub_goal{{ index }}"
                                           v-model="goal.sub[{{ index|add:"-1" }}]">
                                </td>
                                <td>
                                    <button type="button" class="sub_toggle_btn" id="sub_toggle_btn{{ index }}"><div> >> </div></button>
                                </td>
                            </tr>
                        {% endfor %}
                    </table>
                    <button id="delete_button" type="button" class="btn btn-secondary">지우기</button>
                    <input class="btn btn-primary" type="submit">
                </form>
            </div>
            {% for sub_form in sub_forms %}
                <div id="sub_input{{ forloop.counter }}" class="sub_input">
                    <h3>세부목표 {{ forloop.counter }}</h3>
                    <form action="" method="POST">
                        {% csrf_token %}
                        <table>
                            {{ sub_form.as_table }}
                        </table>
                    </form>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

board/templates/board/layout.html
{% extends "layout.html" %}